grails-app/controllers/com/simpragma/assignment/CurrencyAdderController.groovy
package com.simpragma.assignment

import grails.converters.JSON
import grails.plugins.rest.client.RestBuilder
import grails.plugins.rest.client.RestResponse
import org.codehaus.groovy.grails.web.json.JSONObject

class CurrencyAdderController {

    //landing page can be used for
    def index() {

        def currencyList =["USD","INR","AUD","EUR"]

        [currencyList:currencyList]
    }

    // Below line gets wired to the service class by Dependency Injection
    // this is to prevent the controller from having any business logic and becoming bulky
    def currencyConvertorService
    /*
        Below is the action to add values in different given currencies and print the value in the given final currency
    */
    def add(){
//        println(" params ${params} ")
//        def url="https://www.google.com/finance/converter?a=S1&from=C1&to=C2"

        double sourceValue1= params.source1 as double  //value entered for 1st currency
        double sourceValue2= params.source2 as double  //value entered for 2nd currency

        //converting source values to base on 2nd source currency
        double finalSourceValue=0
        def sourceValue=currencyConvertorService.convertCurrency(sourceValue1,params.sourcecurrency1,params.sourcecurrency2)
        if(sourceValue==-1)
            render(view:'error',model:[errors:"Error comverting base currencies"])
        else if(sourceValue==-2)
            render(view:'error',model:[errors:"could not reach internet/network"])
        else
            finalSourceValue=sourceValue+sourceValue2

        //converting sum of the above values in the 2nd currency to final dest currency
        double finalDestValue=0
        def destValue=currencyConvertorService.convertCurrency(finalSourceValue,params.sourcecurrency2,params.destcurrency)
        if(destValue==-1)
            render(view:'error',model:[errors:"Error comverting to final currency"])
        else if(destValue==-2)
            render(view:'error',model:[errors:"could not reach internet/network"])
        else
            finalDestValue=destValue

        finalDestValue = finalDestValue.round(2)
        [value:finalDestValue, currency:params.destcurrency]
    }

    def error(){

    }
}

grails-app/views/currencyAdder/add.gsp
<%--
  Created by IntelliJ IDEA.
  User: vivek
  Date: 16/12/14
  Time: 6:59 AM
--%>

<%@ page contentType="text/html;charset=UTF-8" %>
<html>
<head>
    <title></title>
</head>

<body>
    <h1>${value} in ${currency}</h1>

</body>
</html>

grails-app/views/currencyAdder/error.gsp
<%--
  Created by IntelliJ IDEA.
  User: vivek
  Date: 16/12/14
  Time: 11:19 AM
--%>

<%@ page contentType="text/html;charset=UTF-8" %>
<html>
<head>
    <title>Error</title>
</head>

<body>
    <div>
        Errors found
    </div>
    <div>
        ${errors}
    </div>
</body>
</html>

grails-app/views/currencyAdder/index.gsp
<%--
  Created by IntelliJ IDEA.
  User: vivek
  Date: 16/12/14
  Time: 6:59 AM
--%>

<%@ page contentType="text/html;charset=UTF-8" %>
<html>
<head>
    <title> Currency adder</title>
    <script>
        function validate(){
            var valid_dollar_amt_regex = /^\$?[0-9][0-9]*[0-9]\.?[0-9]{0,2}$/i;
            var source1=document.getElementById("source1").value;
            var source2=document.getElementById("source2").value;
            var destcurr=document.getElementById("destcurrency").value;
            var sourcecurr1=document.getElementById("sourcecurrency1").value;
            var sourcecurr2=document.getElementById("sourcecurrency2").value;
            if(valid_dollar_amt_regex.test(source1) && valid_dollar_amt_regex.test(source2)){
                 if(sourcecurr1=='' || sourcecurr2=='')
                 {
                     alert('please select source currency ');
                     return false;
                 }
                 else if(destcurr==''){
                     alert('please select dest currency');
                     return false;
                 }
                else
                     return true;
            }
            else{
                alert("enter valid currency in numbers")
                return false;
            }

        }
    </script>
</head>

<body>
<g:form controller="currencyAdder" action="add">
    <table width="50%">
        <tr>
            <td>
                Enter the Source Currency 1
            </td>
            <td>
                <input id="source1" name="source1" type="text"/>
            </td>
            <td>
                <g:select name="sourcecurrency1" from="${currencyList}"  noSelection="${['':'Select One...']}"/>
            </td>
        </tr>
        <tr>
            <td>
                Enter Source Currency 2
            </td>
            <td>
                <input id="source2" name="source2" type="text"/>
            </td>
            <td>
                <g:select name="sourcecurrency2" from="${currencyList}"  noSelection="${['':'Select One...']}"/>
            </td>
        </tr>
        <tr>
            <td >
                Enter the final currency
            </td>
            <td colspan="2">
                <g:select id="destcurrency" name="destcurrency" from="${currencyList}"  noSelection="${['':'Select One...']}"/>
            </td>
        </tr>
        <tr>
            <td colspan="3">
                <input name="submit" type="submit" value="submit" onclick="return validate()" />
            </td>
        </tr>
    </table>
</g:form>

</body>
</html>

grails-app/views/layouts/main.gsp
<!DOCTYPE html>
<!--[if lt IE 7 ]> <html lang="en" class="no-js ie6"> <![endif]-->
<!--[if IE 7 ]>    <html lang="en" class="no-js ie7"> <![endif]-->
<!--[if IE 8 ]>    <html lang="en" class="no-js ie8"> <![endif]-->
<!--[if IE 9 ]>    <html lang="en" class="no-js ie9"> <![endif]-->
<!--[if (gt IE 9)|!(IE)]><!--> <html lang="en" class="no-js"><!--<![endif]-->
	<head>
		<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
		<title><g:layoutTitle default="Grails"/></title>
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<link rel="shortcut icon" href="${resource(dir: 'images', file: 'favicon.ico')}" type="image/x-icon">
		<link rel="apple-touch-icon" href="${resource(dir: 'images', file: 'apple-touch-icon.png')}">
		<link rel="apple-touch-icon" sizes="114x114" href="${resource(dir: 'images', file: 'apple-touch-icon-retina.png')}">
		<link rel="stylesheet" href="${resource(dir: 'css', file: 'main.css')}" type="text/css">
		<link rel="stylesheet" href="${resource(dir: 'css', file: 'mobile.css')}" type="text/css">
		<g:layoutHead/>
		<g:javascript library="application"/>		
		<r:layoutResources />
	</head>
	<body>
		<div id="grailsLogo" role="banner"><a href="http://grails.org"><img src="${resource(dir: 'images', file: 'grails_logo.png')}" alt="Grails"/></a></div>
		<g:layoutBody/>
		<div class="footer" role="contentinfo"></div>
		<div id="spinner" class="spinner" style="display:none;"><g:message code="spinner.alt" default="Loading&hellip;"/></div>
		<r:layoutResources />
	</body>
</html>